# Generated by Django 4.1.5 on 2023-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('objects_detected', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'ImageList',
            },
        ),
    ]
