# Generated by Django 4.1.5 on 2023-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to='media/objs/'),
            preserve_default=False,
        ),
    ]
